name: Java CD with CodeDeploy

on:
  workflow_run:
    workflows: [Java CI with Gradle]
    types: 
      - completed
jobs:
  on-success:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
      - name: Instala AWS CLI
        run: sudo apt-get update -y &&
             sudo apt-get upgrade -y &&
             sudo apt-get install awscli -y
      - name: Configurar credenciales de AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      - name: Desplegar aplicación con AWS CodeDeploy
        run: aws deploy create-deployment 
                --region us-east-1
                --application-name HolaMundo 
                --deployment-group-name ImplementacionHolaMundo 
                --revision '{revisionType=GitHub,gitHubLocation={repository="FCedillo98/CodeDeploy",commitId="4e6b74c01f37b5bc6b2ecde9228f4b959a38e256"},fileExistsBehaviour=OVERWRITE}'
  
  on-failure:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
